---
- name: load containers defined in vars/containers
  hosts: all
  sudo: yes
  gather_facts: False
  vars:
    containers:
      - dr.a8.nl/cryptobox/dev
      - busybox
  roles:
    - loadingdocker
